export const FEATURED_PRODUCTS_REQUEST = 'FEATURED_PRODUCTS_REQUEST'
export const FEATURED_PRODUCTS_SUCCESS = 'FEATURED_PRODUCTS_SUCCESS'
export const FEATURED_PRODUCTS_FAIL = 'FEATURED_PRODUCTS_FAIL'

export const LATEST_PRODUCTS_REQUEST = 'LATEST_PRODUCTS_REQUEST'
export const LATEST_PRODUCTS_SUCCESS = 'LATEST_PRODUCTS_SUCCESS'
export const LATEST_PRODUCTS_FAIL = 'LATEST_PRODUCTS_FAIL'

export const DETAILS_PRODUCT_REQUEST = 'DETAILS_PRODUCT_REQUEST'
export const DETAILS_PRODUCT_SUCCESS = 'DETAILS_PRODUCT_SUCCESS'
export const DETAILS_PRODUCT_FAIL = 'DETAILS_PRODUCT_FAIL'

export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'


